[
    [
        datetime.datetime(
            2023,
            4,
            7,
            9,
            30,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
        datetime.datetime(
            2023,
            4,
            7,
            11,
            0,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
    ],
    [
        datetime.datetime(
            2023,
            4,
            7,
            9,
            30,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
        datetime.datetime(
            2023,
            4,
            7,
            11,
            0,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
    ],
    [
        datetime.datetime(
            2023,
            4,
            7,
            11,
            30,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
        datetime.datetime(
            2023,
            4,
            7,
            13,
            0,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
    ],
    [
        datetime.datetime(
            2023,
            4,
            7,
            13,
            30,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
        datetime.datetime(
            2023,
            4,
            7,
            15,
            0,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
    ],
    [
        datetime.datetime(
            2023,
            4,
            7,
            15,
            30,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
        datetime.datetime(
            2023,
            4,
            7,
            16,
            45,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
    ],
    [
        datetime.datetime(
            2023,
            4,
            7,
            9,
            30,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
        datetime.datetime(
            2023,
            4,
            7,
            11,
            0,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
    ],
    [
        datetime.datetime(
            2023,
            4,
            7,
            11,
            30,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
        datetime.datetime(
            2023,
            4,
            7,
            13,
            0,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
    ],
    [
        datetime.datetime(
            2023,
            4,
            7,
            13,
            30,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
        datetime.datetime(
            2023,
            4,
            7,
            15,
            0,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
    ],
    [
        datetime.datetime(
            2023,
            4,
            7,
            15,
            30,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
        datetime.datetime(
            2023,
            4,
            7,
            17,
            0,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
    ],
    [
        datetime.datetime(
            2023,
            4,
            7,
            9,
            30,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
        datetime.datetime(
            2023,
            4,
            7,
            11,
            0,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
    ],
    [
        datetime.datetime(
            2023,
            4,
            7,
            11,
            30,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
        datetime.datetime(
            2023,
            4,
            7,
            13,
            0,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
    ],
    [
        datetime.datetime(
            2023,
            4,
            7,
            13,
            30,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
        datetime.datetime(
            2023,
            4,
            7,
            15,
            0,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
    ],
    [
        datetime.datetime(
            2023,
            4,
            7,
            15,
            30,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
        datetime.datetime(
            2023,
            4,
            7,
            17,
            0,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
    ],
    [
        datetime.datetime(
            2023,
            4,
            7,
            17,
            30,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
        datetime.datetime(
            2023,
            4,
            7,
            19,
            0,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
    ],
    [
        datetime.datetime(
            2023,
            4,
            7,
            19,
            30,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
        datetime.datetime(
            2023,
            4,
            7,
            20,
            45,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
    ],
    [
        datetime.datetime(
            2023,
            4,
            7,
            9,
            30,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
        datetime.datetime(
            2023,
            4,
            7,
            11,
            0,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
    ],
    [
        datetime.datetime(
            2023,
            4,
            7,
            11,
            30,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
        datetime.datetime(
            2023,
            4,
            7,
            13,
            0,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
    ],
    [
        datetime.datetime(
            2023,
            4,
            7,
            13,
            30,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
        datetime.datetime(
            2023,
            4,
            7,
            15,
            0,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
    ],
    [
        datetime.datetime(
            2023,
            4,
            7,
            15,
            30,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
        datetime.datetime(
            2023,
            4,
            7,
            17,
            0,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
    ],
    [
        datetime.datetime(
            2023,
            4,
            7,
            17,
            30,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
        datetime.datetime(
            2023,
            4,
            7,
            19,
            0,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
    ],
    [
        datetime.datetime(
            2023,
            4,
            7,
            19,
            30,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
        datetime.datetime(
            2023,
            4,
            7,
            21,
            0,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
    ],
    [
        datetime.datetime(
            2023,
            4,
            7,
            9,
            30,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
        datetime.datetime(
            2023,
            4,
            7,
            11,
            0,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
    ],
    [
        datetime.datetime(
            2023,
            4,
            7,
            11,
            30,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
        datetime.datetime(
            2023,
            4,
            7,
            13,
            0,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
    ],
    [
        datetime.datetime(
            2023,
            4,
            7,
            13,
            30,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
        datetime.datetime(
            2023,
            4,
            7,
            15,
            0,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
    ],
    [
        datetime.datetime(
            2023,
            4,
            7,
            15,
            30,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
        datetime.datetime(
            2023,
            4,
            7,
            17,
            0,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
    ],
    [
        datetime.datetime(
            2023,
            4,
            7,
            17,
            30,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
        datetime.datetime(
            2023,
            4,
            7,
            19,
            0,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
    ],
    [
        datetime.datetime(
            2023,
            4,
            7,
            19,
            30,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
        datetime.datetime(
            2023,
            4,
            7,
            21,
            0,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
    ],
    [
        datetime.datetime(
            2023,
            4,
            7,
            21,
            30,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
        datetime.datetime(
            2023,
            4,
            7,
            22,
            15,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
    ],
]
