[
    (
        datetime.datetime(
            2023,
            4,
            1,
            9,
            50,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
        datetime.datetime(
            2023,
            4,
            1,
            11,
            20,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
    ),
    (
        datetime.datetime(
            2023,
            4,
            1,
            11,
            50,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
        datetime.datetime(
            2023,
            4,
            1,
            13,
            0,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
    ),
    (
        datetime.datetime(
            2023,
            4,
            1,
            14,
            0,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
        datetime.datetime(
            2023,
            4,
            1,
            15,
            30,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
    ),
    (
        datetime.datetime(
            2023,
            4,
            1,
            16,
            0,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
        datetime.datetime(
            2023,
            4,
            1,
            17,
            30,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
    ),
    (
        datetime.datetime(
            2023,
            4,
            1,
            19,
            0,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
        datetime.datetime(
            2023,
            4,
            1,
            20,
            30,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
    ),
    (
        datetime.datetime(
            2023,
            4,
            1,
            21,
            30,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
        datetime.datetime(
            2023,
            4,
            1,
            22,
            0,
            tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)),
        ),
    ),
]
