[
    {
        "added_at": "2022-12-17T12:14:32.945673Z",
        "added_by_uid": "39152655",
        "assigned_by_uid": None,
        "checked": False,
        "child_order": 28,
        "collapsed": False,
        "completed_at": None,
        "content": "send dad food costs",
        "day_order": 20,
        "description": "0:15",
        "due": {
            "date": "2023-04-22",
            "is_recurring": False,
            "lang": "en",
            "string": "Apr 22",
            "timezone": None,
        },
        "id": "6445019003",
        "is_deleted": False,
        "labels": [],
        "parent_id": None,
        "priority": 1,
        "project_id": "2304252052",
        "responsible_uid": None,
        "section_id": None,
        "sync_id": None,
        "user_id": "39152655",
    },
    {
        "added_at": "2022-12-17T22:05:43.399767Z",
        "added_by_uid": "39152655",
        "assigned_by_uid": None,
        "checked": False,
        "child_order": 1,
        "collapsed": True,
        "completed_at": None,
        "content": "Cleaning",
        "day_order": 7,
        "description": "1:15",
        "due": {
            "date": "2023-04-22",
            "is_recurring": True,
            "lang": "en",
            "string": "every sat",
            "timezone": None,
        },
        "id": "6446010422",
        "is_deleted": False,
        "labels": [],
        "parent_id": None,
        "priority": 4,
        "project_id": "2304254239",
        "responsible_uid": None,
        "section_id": None,
        "sync_id": None,
        "user_id": "39152655",
    },
    {
        "added_at": "2022-12-18T04:22:03.279064Z",
        "added_by_uid": "39152655",
        "assigned_by_uid": None,
        "checked": False,
        "child_order": 2,
        "collapsed": False,
        "completed_at": None,
        "content": "Figure out food meals and get into cooking",
        "day_order": -1,
        "description": "",
        "due": None,
        "id": "6446347511",
        "is_deleted": False,
        "labels": [],
        "parent_id": None,
        "priority": 2,
        "project_id": "2304239989",
        "responsible_uid": None,
        "section_id": None,
        "sync_id": None,
        "user_id": "39152655",
    },
    {
        "added_at": "2022-12-18T04:22:13.475132Z",
        "added_by_uid": "39152655",
        "assigned_by_uid": None,
        "checked": False,
        "child_order": 3,
        "collapsed": False,
        "completed_at": None,
        "content": "Return amazon products",
        "day_order": -1,
        "description": "",
        "due": None,
        "id": "6446347651",
        "is_deleted": False,
        "labels": [],
        "parent_id": None,
        "priority": 3,
        "project_id": "2304239989",
        "responsible_uid": None,
        "section_id": None,
        "sync_id": None,
        "user_id": "39152655",
    },
    {
        "added_at": "2022-12-18T04:27:27.295945Z",
        "added_by_uid": "39152655",
        "assigned_by_uid": None,
        "checked": False,
        "child_order": 4,
        "collapsed": False,
        "completed_at": None,
        "content": "Card Payments (Discover, Chase)",
        "day_order": 5,
        "description": "0:15",
        "due": {
            "date": "2023-04-30",
            "is_recurring": True,
            "lang": "en",
            "string": "every 30th",
            "timezone": None,
        },
        "id": "6446351566",
        "is_deleted": False,
        "labels": [],
        "parent_id": None,
        "priority": 4,
        "project_id": "2304254239",
        "responsible_uid": None,
        "section_id": None,
        "sync_id": None,
        "user_id": "39152655",
    },
    {
        "added_at": "2022-12-20T07:29:25.038119Z",
        "added_by_uid": "39152655",
        "assigned_by_uid": None,
        "checked": False,
        "child_order": 5,
        "collapsed": False,
        "completed_at": None,
        "content": "Make trading bot that tracks the trades of US senators",
        "day_order": -1,
        "description": "",
        "due": None,
        "id": "6452070426",
        "is_deleted": False,
        "labels": [],
        "parent_id": None,
        "priority": 3,
        "project_id": "2304239989",
        "responsible_uid": None,
        "section_id": None,
        "sync_id": None,
        "user_id": "39152655",
    },
    {
        "added_at": "2022-12-23T08:49:30.515013Z",
        "added_by_uid": "39152655",
        "assigned_by_uid": None,
        "checked": False,
        "child_order": 8,
        "collapsed": False,
        "completed_at": None,
        "content": "Brainstorm ways to make money and gain a following",
        "day_order": -1,
        "description": "",
        "due": None,
        "id": "6461147703",
        "is_deleted": False,
        "labels": [],
        "parent_id": None,
        "priority": 2,
        "project_id": "2304239989",
        "responsible_uid": None,
        "section_id": None,
        "sync_id": None,
        "user_id": "39152655",
    },
    {
        "added_at": "2022-12-29T04:59:13.992338Z",
        "added_by_uid": "39152655",
        "assigned_by_uid": None,
        "checked": False,
        "child_order": 5,
        "collapsed": False,
        "completed_at": None,
        "content": "Make Weekly Goals",
        "day_order": 11,
        "description": "0:15",
        "due": {
            "date": "2023-04-23",
            "is_recurring": True,
            "lang": "en",
            "string": "every sunday",
            "timezone": None,
        },
        "id": "6472977185",
        "is_deleted": False,
        "labels": [],
        "parent_id": None,
        "priority": 3,
        "project_id": "2304254239",
        "responsible_uid": None,
        "section_id": None,
        "sync_id": None,
        "user_id": "39152655",
    },
    {
        "added_at": "2023-01-03T17:27:20.340278Z",
        "added_by_uid": "39152655",
        "assigned_by_uid": None,
        "checked": False,
        "child_order": 30,
        "collapsed": False,
        "completed_at": None,
        "content": "write review for Man's Search for Meaning",
        "day_order": 17,
        "description": "0:45",
        "due": {
            "date": "2023-04-22",
            "is_recurring": False,
            "lang": "en",
            "string": "Apr 22",
            "timezone": None,
        },
        "id": "6486965522",
        "is_deleted": False,
        "labels": [],
        "parent_id": None,
        "priority": 2,
        "project_id": "2304252052",
        "responsible_uid": None,
        "section_id": None,
        "sync_id": None,
        "user_id": "39152655",
    },
    {
        "added_at": "2023-03-07T19:35:07.778726Z",
        "added_by_uid": "39152655",
        "assigned_by_uid": None,
        "checked": False,
        "child_order": 62,
        "collapsed": False,
        "completed_at": None,
        "content": "figure out leasing",
        "day_order": 9,
        "description": "1:15",
        "due": {
            "date": "2023-04-22",
            "is_recurring": False,
            "lang": "en",
            "string": "Apr 22",
            "timezone": None,
        },
        "id": "6681157109",
        "is_deleted": False,
        "labels": [],
        "parent_id": None,
        "priority": 4,
        "project_id": "2304252052",
        "responsible_uid": None,
        "section_id": None,
        "sync_id": None,
        "user_id": "39152655",
    },
    {
        "added_at": "2023-03-16T06:37:08.611539Z",
        "added_by_uid": "39152655",
        "assigned_by_uid": None,
        "checked": False,
        "child_order": 64,
        "collapsed": False,
        "completed_at": None,
        "content": "summarize lessons from notes into notion",
        "day_order": 18,
        "description": "0:30",
        "due": {
            "date": "2023-04-22",
            "is_recurring": False,
            "lang": "en",
            "string": "Apr 22",
            "timezone": None,
        },
        "id": "6706189164",
        "is_deleted": False,
        "labels": [],
        "parent_id": None,
        "priority": 2,
        "project_id": "2304252052",
        "responsible_uid": None,
        "section_id": None,
        "sync_id": None,
        "user_id": "39152655",
    },
    {
        "added_at": "2023-03-18T16:25:33.386801Z",
        "added_by_uid": "39152655",
        "assigned_by_uid": None,
        "checked": False,
        "child_order": 29,
        "collapsed": False,
        "completed_at": None,
        "content": "plant other bonsai trees",
        "day_order": 19,
        "description": "0:30",
        "due": {
            "date": "2023-04-22",
            "is_recurring": False,
            "lang": "en",
            "string": "Apr 22",
            "timezone": None,
        },
        "id": "6713014970",
        "is_deleted": False,
        "labels": [],
        "parent_id": None,
        "priority": 2,
        "project_id": "2304252052",
        "responsible_uid": None,
        "section_id": None,
        "sync_id": None,
        "user_id": "39152655",
    },
    {
        "added_at": "2023-03-22T21:17:08.123506Z",
        "added_by_uid": "39152655",
        "assigned_by_uid": None,
        "checked": False,
        "child_order": 69,
        "collapsed": False,
        "completed_at": None,
        "content": "garden work",
        "day_order": 2,
        "description": "0:30",
        "due": {
            "date": "2023-04-22",
            "is_recurring": True,
            "lang": "en",
            "string": "every day",
            "timezone": None,
        },
        "id": "6725915700",
        "is_deleted": False,
        "labels": [],
        "parent_id": None,
        "priority": 4,
        "project_id": "2304252052",
        "responsible_uid": None,
        "section_id": None,
        "sync_id": None,
        "user_id": "39152655",
    },
    {
        "added_at": "2023-03-26T19:04:33.388825Z",
        "added_by_uid": "39152655",
        "assigned_by_uid": None,
        "checked": False,
        "child_order": 70,
        "collapsed": False,
        "completed_at": None,
        "content": "clean up code for my finance scraper",
        "day_order": 16,
        "description": "1:00",
        "due": {
            "date": "2023-04-22",
            "is_recurring": False,
            "lang": "en",
            "string": "Apr 22",
            "timezone": None,
        },
        "id": "6735890313",
        "is_deleted": False,
        "labels": [],
        "parent_id": None,
        "priority": 2,
        "project_id": "2304252052",
        "responsible_uid": None,
        "section_id": None,
        "sync_id": None,
        "user_id": "39152655",
    },
    {
        "added_at": "2023-03-27T07:36:05.042782Z",
        "added_by_uid": "39152655",
        "assigned_by_uid": None,
        "checked": False,
        "child_order": 71,
        "collapsed": False,
        "completed_at": None,
        "content": "clean car washing equipment",
        "day_order": 15,
        "description": "0:30",
        "due": {
            "date": "2023-04-22",
            "is_recurring": False,
            "lang": "en",
            "string": "Apr 22",
            "timezone": None,
        },
        "id": "6737204981",
        "is_deleted": False,
        "labels": [],
        "parent_id": None,
        "priority": 3,
        "project_id": "2304252052",
        "responsible_uid": None,
        "section_id": None,
        "sync_id": None,
        "user_id": "39152655",
    },
    {
        "added_at": "2023-03-27T08:14:51.558271Z",
        "added_by_uid": "39152655",
        "assigned_by_uid": None,
        "checked": False,
        "child_order": 9,
        "collapsed": False,
        "completed_at": None,
        "content": "plan when to meet Sunny",
        "day_order": -1,
        "description": "",
        "due": None,
        "id": "6737317971",
        "is_deleted": False,
        "labels": [],
        "parent_id": None,
        "priority": 4,
        "project_id": "2304239989",
        "responsible_uid": None,
        "section_id": None,
        "sync_id": None,
        "user_id": "39152655",
    },
    {
        "added_at": "2023-03-29T03:59:25.140091Z",
        "added_by_uid": "39152655",
        "assigned_by_uid": None,
        "checked": False,
        "child_order": 73,
        "collapsed": False,
        "completed_at": None,
        "content": "find optician and sunglasses",
        "day_order": 14,
        "description": "1:00",
        "due": {
            "date": "2023-04-22",
            "is_recurring": False,
            "lang": "en",
            "string": "Apr 22",
            "timezone": None,
        },
        "id": "6743763972",
        "is_deleted": False,
        "labels": [],
        "parent_id": None,
        "priority": 3,
        "project_id": "2304252052",
        "responsible_uid": None,
        "section_id": None,
        "sync_id": None,
        "user_id": "39152655",
    },
    {
        "added_at": "2023-04-02T01:51:35.286255Z",
        "added_by_uid": "39152655",
        "assigned_by_uid": None,
        "checked": False,
        "child_order": 6,
        "collapsed": False,
        "completed_at": None,
        "content": "Korean",
        "day_order": 5,
        "description": "0:45",
        "due": {
            "date": "2023-04-22",
            "is_recurring": True,
            "lang": "en",
            "string": "every day",
            "timezone": None,
        },
        "id": "6755072019",
        "is_deleted": False,
        "labels": [],
        "parent_id": None,
        "priority": 4,
        "project_id": "2304254239",
        "responsible_uid": None,
        "section_id": None,
        "sync_id": None,
        "user_id": "39152655",
    },
    {
        "added_at": "2023-04-02T01:53:09.335925Z",
        "added_by_uid": "39152655",
        "assigned_by_uid": None,
        "checked": False,
        "child_order": 8,
        "collapsed": False,
        "completed_at": None,
        "content": "Read",
        "day_order": 10,
        "description": "0:30",
        "due": {
            "date": "2023-04-22",
            "is_recurring": True,
            "lang": "en",
            "string": "every day",
            "timezone": None,
        },
        "id": "6755073501",
        "is_deleted": False,
        "labels": [],
        "parent_id": None,
        "priority": 4,
        "project_id": "2304254239",
        "responsible_uid": None,
        "section_id": None,
        "sync_id": None,
        "user_id": "39152655",
    },
    {
        "added_at": "2023-04-02T01:53:25.628569Z",
        "added_by_uid": "39152655",
        "assigned_by_uid": None,
        "checked": False,
        "child_order": 7,
        "collapsed": False,
        "completed_at": None,
        "content": "Memorization",
        "day_order": 6,
        "description": "0:30",
        "due": {
            "date": "2023-04-22",
            "is_recurring": True,
            "lang": "en",
            "string": "every day",
            "timezone": None,
        },
        "id": "6755073719",
        "is_deleted": False,
        "labels": [],
        "parent_id": None,
        "priority": 4,
        "project_id": "2304254239",
        "responsible_uid": None,
        "section_id": None,
        "sync_id": None,
        "user_id": "39152655",
    },
    {
        "added_at": "2023-04-02T03:11:19.527071Z",
        "added_by_uid": "39152655",
        "assigned_by_uid": None,
        "checked": False,
        "child_order": 68,
        "collapsed": False,
        "completed_at": None,
        "content": "find food ideas",
        "day_order": 13,
        "description": "0:45",
        "due": {
            "date": "2023-04-22",
            "is_recurring": False,
            "lang": "en",
            "string": "Apr 22",
            "timezone": None,
        },
        "id": "6755139420",
        "is_deleted": False,
        "labels": [],
        "parent_id": None,
        "priority": 3,
        "project_id": "2304252052",
        "responsible_uid": None,
        "section_id": None,
        "sync_id": None,
        "user_id": "39152655",
    },
    {
        "added_at": "2023-04-09T04:40:48.392384Z",
        "added_by_uid": "39152655",
        "assigned_by_uid": None,
        "checked": False,
        "child_order": 9,
        "collapsed": False,
        "completed_at": None,
        "content": "piano",
        "day_order": 3,
        "description": "0:30",
        "due": {
            "date": "2023-04-22",
            "is_recurring": True,
            "lang": "en",
            "string": "every day",
            "timezone": None,
        },
        "id": "6775254568",
        "is_deleted": False,
        "labels": [],
        "parent_id": None,
        "priority": 4,
        "project_id": "2304254239",
        "responsible_uid": None,
        "section_id": None,
        "sync_id": None,
        "user_id": "39152655",
    },
    {
        "added_at": "2023-04-09T06:35:11.271422Z",
        "added_by_uid": "39152655",
        "assigned_by_uid": None,
        "checked": False,
        "child_order": 77,
        "collapsed": False,
        "completed_at": None,
        "content": "plan Victoria Trip",
        "day_order": 8,
        "description": "0:45",
        "due": {
            "date": "2023-04-22",
            "is_recurring": False,
            "lang": "en",
            "string": "Apr 22",
            "timezone": None,
        },
        "id": "6775342674",
        "is_deleted": False,
        "labels": [],
        "parent_id": None,
        "priority": 4,
        "project_id": "2304252052",
        "responsible_uid": None,
        "section_id": None,
        "sync_id": None,
        "user_id": "39152655",
    },
    {
        "added_at": "2023-04-17T21:48:51.414855Z",
        "added_by_uid": "39152655",
        "assigned_by_uid": None,
        "checked": False,
        "child_order": 83,
        "collapsed": False,
        "completed_at": None,
        "content": "sell drums lol",
        "day_order": 11,
        "description": "1:00",
        "due": {
            "date": "2023-04-22",
            "is_recurring": False,
            "lang": "en",
            "string": "Apr 22",
            "timezone": None,
        },
        "id": "6800591988",
        "is_deleted": False,
        "labels": [],
        "parent_id": None,
        "priority": 4,
        "project_id": "2304252052",
        "responsible_uid": None,
        "section_id": None,
        "sync_id": None,
        "user_id": "39152655",
    },
    {
        "added_at": "2023-04-18T18:12:58.534041Z",
        "added_by_uid": "39152655",
        "assigned_by_uid": None,
        "checked": False,
        "child_order": 85,
        "collapsed": False,
        "completed_at": None,
        "content": "work on scheduler",
        "day_order": 4,
        "description": "0:45",
        "due": {
            "date": "2023-04-22",
            "is_recurring": False,
            "lang": "en",
            "string": "Apr 22",
            "timezone": None,
        },
        "id": "6803464774",
        "is_deleted": False,
        "labels": [],
        "parent_id": None,
        "priority": 4,
        "project_id": "2304252052",
        "responsible_uid": None,
        "section_id": None,
        "sync_id": None,
        "user_id": "39152655",
    },
    {
        "added_at": "2023-04-23T00:37:04.103576Z",
        "added_by_uid": "39152655",
        "assigned_by_uid": None,
        "checked": False,
        "child_order": 86,
        "collapsed": False,
        "completed_at": None,
        "content": "test",
        "day_order": 21,
        "description": "0:15",
        "due": {
            "date": "2023-04-22",
            "is_recurring": False,
            "lang": "en",
            "string": "Apr 22",
            "timezone": None,
        },
        "id": "6815332021",
        "is_deleted": False,
        "labels": [],
        "parent_id": None,
        "priority": 1,
        "project_id": "2304252052",
        "responsible_uid": None,
        "section_id": None,
        "sync_id": None,
        "user_id": "39152655",
    },
    {
        "added_at": "2023-04-23T00:40:36.416681Z",
        "added_by_uid": "39152655",
        "assigned_by_uid": None,
        "checked": False,
        "child_order": 87,
        "collapsed": False,
        "completed_at": None,
        "content": "test2",
        "day_order": 12,
        "description": "",
        "due": {
            "date": "2023-04-22",
            "is_recurring": False,
            "lang": "en",
            "string": "Apr 22",
            "timezone": None,
        },
        "id": "6815334885",
        "is_deleted": False,
        "labels": [],
        "parent_id": None,
        "priority": 4,
        "project_id": "2304252052",
        "responsible_uid": None,
        "section_id": None,
        "sync_id": None,
        "user_id": "39152655",
    },
    {
        "added_at": "2023-04-23T00:40:51.377651Z",
        "added_by_uid": "39152655",
        "assigned_by_uid": None,
        "checked": False,
        "child_order": 88,
        "collapsed": False,
        "completed_at": None,
        "content": "get aquaphor",
        "day_order": 1,
        "description": "",
        "due": {
            "date": "2023-04-22",
            "is_recurring": False,
            "lang": "en",
            "string": "Apr 22",
            "timezone": None,
        },
        "id": "6815335087",
        "is_deleted": False,
        "labels": [],
        "parent_id": None,
        "priority": 4,
        "project_id": "2304252052",
        "responsible_uid": None,
        "section_id": None,
        "sync_id": None,
        "user_id": "39152655",
    },
]
